CREATE DATABASE POE_DOMINGOROOFWORKS_16012775;

CREATE TABLE CUSTOMER
(
CUSTOMER_ID VARCHAR(80) NOT NULL,
CUSTOMER_NAME VARCHAR(100) NOT NULL,
CUSTOMER_SURNAME VARCHAR(100) NOT NULL,
CUSTOMER_ADDRESS VARCHAR(100) NOT NULL,
CUSTOMER__PROVINCE VARCHAR(80) NOT NULL,
CUSTOMER_ZIPCODE VARCHAR(10) NOT NULL,
PRIMARY KEY(CUSTOMER_ID)
)

CREATE TABLE JOB_TYPES
(
JOB_TYPE_ID INT NOT NULL,
JOB_TYPE VARCHAR(80) NOT NULL,
DAILY_RATE DECIMAL NOT NULL,
PRIMARY KEY(JOB_TYPE_ID)
)

CREATE TABLE JOBS
(
JOB_CARD_NO INT NOT NULL,
JOB_TYPE_ID INT FOREIGN KEY REFERENCES JOB_TYPES(JOB_TYPE_ID),
NO_OF_DAYS INT NOT NULL,
CUSTOMER_ID VARCHAR(80) FOREIGN KEY REFERENCES CUSTOMER(CUSTOMER_ID),
PRIMARY KEY(JOB_CARD_NO)
)

CREATE TABLE EMPLOYEES
(
EMPLOYEE_NO VARCHAR(80) NOT NULL,
EMPLOYEE_NAME VARCHAR(80) NOT NULL,
EMPLOYEE_SURNAME VARCHAR(80) NOT NULL,
PRIMARY KEY(EMPLOYEE_NO)
)
CREATE TABLE EMPLOYEES_JOBS
(
EMP_JOB_ID VARCHAR(30) NOT NULL,
JOB_CARD_NO INT FOREIGN KEY REFERENCES JOBS(JOB_CARD_NO),
EMPLOYEE_NO VARCHAR (80) FOREIGN KEY REFERENCES EMPLOYEES(EMPLOYEE_NO),
PRIMARY KEY(EMP_JOB_ID)
)
CREATE TABLE MATERIALS
(
MAT_ID INT NOT NULL,
MAT_TYPE VARCHAR(100) NOT NULL,
PRIMARY KEY(MAT_ID)
)

CREATE TABLE MATERIALS_PER_PROJECT
(
MAT_PROJECT_ID VARCHAR(20) NOT NULL,
JOB_CARD_NO INT FOREIGN KEY REFERENCES JOBS(JOB_CARD_NO),
MAT_ID INT FOREIGN KEY REFERENCES MATERIALS(MAT_ID),
QUANTITY INT NOT NULL
PRIMARY KEY(MAT_PROJECT_ID)
)
CREATE TABLE INVOICE( 
INVOICE_ID VARCHAR(80) NOT NULL PRIMARY KEY, 
JOB_CARD_NUMBER INT not null, 
foreign key (job_card_number) references JOBS(JOB_CARD_NO),
customer_id VARCHAR(80) not null, 
foreign key (customer_id) references customer(customer_id), 
job_card_id int not null, 
foreign key (job_card_id) references JOB_TYPES(JOB_TYPE_ID), 
job_id int not null, 
foreign key (job_id) references JOBS(JOB_CARD_NO), 
invoice_amount decimal(8,2) not null, 
); 