--2.1--
CREATE DATABASE DATA6212_EXAM2018q2

        CREATE TABLE INTERNS
        (
            INTERN_ID VARCHAR(5),
            INTERN_NAME NVARCHAR(40) NOT NULL,
            INTERN_SURNAME NVARCHAR(40) NOT NULL,
            DATE_OF_BIRTH SMALLINT NOT NULL, 
        )

        CREATE TABLE DERPARTMENTS
        (
            DERPARTMENT_ID VARCHAR(5),
            DEPARTMENT_NAME VARCHAR(20) NOT NULL,
        )

        CREATE TABLE EXPERIENCE
        (
            INTERN_ID VARCHAR(5),
            DEPARTMENT_ID VARCHAR(5),
            NUMBER_OF_DAYS SMALLINT NOT NULL            
        )

--2.2--
ALTER TABLE INTERNS ADD AGE SMALLINT

UPDATE INTERNS SET AGE = DATEDIFF(YY.DATE_OF_BIRTH.GETDATE())
FROM INTERNS
SELECT * FROM INTERNS


--2.3--
SELECT I.INTERN_NAME, I.INTERN_SURNAME, SUM(E.NUMBER_OF_DAYS) AS
'TOTAL DAYS WORKED'
FROM INTERNS I
LEFT OUTER JOIN EXPERIENCE E ON I.INTERN_ID = E.INTERN_ID
GROUP BY I.INTERN_NAME, I.INTERN_SURNAME, I.INTERN_ID
ORDER BY SUM(E.NUMBER_OF_DAYS)DESC

--2.4--
SELECT * FROM DERPARTMENTS 
WHERE DEPARTMENT_NAME LIKE ('%DESIGN%')

--2.5--
SELECT TOP 1 I.INTERN_NAME, I.INTERN_SURNAME, D.DEPARTMENT_NAME,
E.NUMBER_OF_DAYS FROM INTERNS I, DERPARTMENTS D, EXPERIENCE E
WHERE I.INTERN_ID = E.INTERN_ID AND
D.DERPARTMENT_ID = E.DEPARTMENT_ID AND
E.DEPARTMENT_ID = 'D0001'
ORDER BY E.NUMBER_OF_DAYS DESC