CREATE VIEW NovemberLongSessions
AS 
SELECT VENUE_ID, MODULE_CODE, BOOKING_DATE, STARTING_TIME, DURATION
FROM VENUE_BOOKINGS
WHERE DURATION >= 100

SELECT VENUE_ID, MODULE_CODE, BOOKING_DATE, STARTING_TIME, DURATION
FROM     dbo.VENUE_BOOKINGS
WHERE  (DURATION >= 100)




