Create PROCEDURE FindModuleBooks @MODULE_CODE NVARCHAR(10)
AS 
SELECT VENUE_NAME, BOOKING_DATE, STARTING_TIME, DURATION 
FROM VENUE_BOOKINGS, VENUES
WHERE module_code = @MODULE_CODE

EXEC FindModuleBooks @MODULE_CODE = 'WEDE220';

