SELECT DISTINCT MODULE_CODE, MODULE_NAME






SElECT DISTINCT MODULE_NAME,
CASE 
	WHEN BOOKING_DATE LIKE '2018%' THEN 'BOOKING RECORDED'
	WHEN BOOKING_DATE LIKE '2018%' THEN 'No Bookings recorded' 
END AS "BOOKING STATUS"
FROM MODULES, VENUE_BOOKINGS